name: Publish
on: 
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          path: 'source'
      - name: Generate from source
        run: cd source; swift run; cd ..
      - uses: actions/checkout@v2
        with:
          ref: 'generated'
          path: 'generated'
      - name: Publish
        run: |
          cd generated
          find . -type d -not -ipath "./.git*" -delete
          mv ../source/Output/* .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Generated automatically based on $GITHUB_SHA"
          git push origin
      - run: echo "Published!"
